### ISSUE TITLE
geting the json

### ISSUE THREAD

**Issue by cadubra** [Sobesednik/node-exiftool#16]
Hi, great project. Do you have an example of a callback? I need to get the data in json, send database.

**Comment by z-vr** [comment]
@cadubra I've added a callback example: https://github.com/Sobesednik/node-exiftool/blob/master/examples/callback.js

**Comment by cadubra** [comment]
I forgot to thank, it worked perfect. Thank you very much

2017-02-09 20:10 GMT-02:00 Anton <notifications@github.com>:
