### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by neojski** [Sobesednik/node-exiftool#20]
I was trying node-exiftool on windows in cygwin but had I experience some problems with encoding. Please note that dist-exiftool works fine whilst node-exiftool does not:

```js
const execFile = require('child_process').execFile;
const exiftoolBin = require('dist-exiftool');
const exiftool = require('node-exiftool')

const file = 'zdjęcie.jpg';

execFile(exiftoolBin, ['-j', file], (error, stdout, stderr) => {
        if (error) {
                console.error(`exec error: ${error}`);
                return;
        }
        console.log('raw:');
        console.log(stdout);
});

const ep = new exiftool.ExiftoolProcess(exiftoolBin)
ep.open()
        .then(() => ep.readMetadata(file))
        .then(result => {
                console.log('advanced:');
                console.log(result);
        })
        .then(() => ep.close());
```

> raw:
> [{
>   "SourceFile": "zdj?cie.jpg",
>   "ExifToolVersion": 10.33,
>   "FileName": "zdj?cie.jpg",
>   "Directory": ".",
>   "Warning": "FileName encoding not specified",
>   ...
> }]
> 
> advanced:
> { data: null, error: 'File not found: zdjęcie.jpg' }

Also, please note that running exiftool directly doesn't print garbled file name:

```bash
$ ./node_modules/exiftool.pl/vendor/exiftool zdjęcie.jpg
ExifTool Version Number         : 10.33
File Name                       : zdjęcie.jpg
Directory                       : .
...
```

**Comment by z-vr** [comment]
@neojski could you give the filepath as absolute directory and see what happens? e.g.,
```
const path = require('path')
const file = path.join(__dirname, 'zdjęcie.jpg') // assuming the file is in the same directory

```

**Comment by z-vr** [comment]
@neojski you are right, on Windows it cannot read the file: https://github.com/Sobesednik/node-exiftool/pull/24

**Comment by z-vr** [comment]
You have to pass `['charset filename=utf8']` as argument, e.g., `ep.readMetadata('zdjęcie.jpg', ['charset filename=utf8'])`

[passing build](https://ci.appveyor.com/project/zavr-1/node-exiftool/build/1.0.117)
[test](https://github.com/Sobesednik/node-exiftool/pull/24/files#diff-7a591414d177e1d2e7f9ca099d194fa4R33)

http://www.sno.phy.queensu.ca/~phil/exiftool/faq.html#Q18
http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=6721.0

**Comment by neojski** [comment]
I don't have a windows machine on hand now but this looks pretty convincing. Thanks!

**Comment by z-vr** [comment]
@neojski cool thanks for raising the issue! 👍
