### ISSUE TITLE
Add possibility to specify options to child_process.spawn

### ISSUE THREAD

**Issue by mika-fischer** [Sobesednik/node-exiftool#33]
In particular I need to pass `{detached: true}`. The reason is that when an application is interrupted by Ctrl-C, all child processes also receive `SIGINT` including the exiftool process. I would like to shield the exiftool process from that in order to be able to shut down my application in a controlled fashion.

**Comment by z-vr** [comment]
@mika-fischer ok i'll do it

**Comment by z-vr** [comment]
@mika-fischer sorry for the delay, I'll be releasing [this feature](https://github.com/Sobesednik/node-exiftool/pull/35) tomorrow.

**Comment by z-vr** [comment]
@mika-fischer thanks for opening this issue. The feature has landed in `node-exiftool@2.3.0`. Please beware that `conhost.exe` and a second `exiftool.exe` process will be open by `exiftool` on Windows platform -- which you then need to kill manually if you want to handle exit gracefully. See [readme](https://github.com/Sobesednik/node-exiftool#using-detached-mode-on-windows) and [test](https://github.com/Sobesednik/node-exiftool/blob/master/test/spec/detached-true.js#L158).
