### ISSUE TITLE
unable to retrieve a tag data in php

### ISSUE THREAD

**Issue by MahmoudYaser1** [Sobesednik/node-exiftool#42]
i am working on a project uses this library to store some information inside exif data in an image ... it works just fine with images that have ExifByteOrder=Little-endian
take a look at the Comment tag 
![untitled-1](https://user-images.githubusercontent.com/23610404/38330024-c689c8d4-384f-11e8-9c34-7b7957e92c7d.jpg)
but it doesn't work with ExifByteOrder=Big-endian
![untitled-2](https://user-images.githubusercontent.com/23610404/38330053-dbade3d0-384f-11e8-91fe-bd500b99e19c.jpg)

i found this 
http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=3539.0
to modifying the ExifByteOrder
and i tried it using your library but with no success .. can you please help me !!

**Comment by dekemega** [comment]
Hi .. Mr.Phil solve this issue but we need to implement it with your module

[link](http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,9074.0.html)

**Comment by MahmoudYaser1** [comment]
Hi, Mr.Phil solve this[ in this thread ](http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,9074.0.html) so we can implement it now by using it in the args like this
ep.writeMetadata('destination.jpg', { metadata }, [args]))
Thanks to [Mr.Phil Harvey](http://u88.n24.queensu.ca/exiftool/forum/index.php?action=profile;u=1)
