### ISSUE TITLE
readMetadata options not working

### ISSUE THREAD

**Issue by ndtreviv** [Sobesednik/node-exiftool#48]
If I extract with OPTIONS:
```
const OPTIONS = [
  "-u",
  "-F",
  "-c",
  "%+.5f",
  "GPSLatitude",
  "GPSLongitude",
  "GPSLatitudeRef",
  "GPSLongitudeRef"
];

...

ep.readMetadata(filePath, OPTIONS)
```

then it doesn't format the GPS Longitude correctly - the `-c %+.5f` gets ignored.

I've also tried combining the two into a single array entry with no joy.

I also want `-F` and `-u` to work.

**Comment by zavr-1** [comment]
hi i'll have a look today sorry i'm super busy i do see your messages

**Comment by ndtreviv** [comment]
No worries - at the moment I'm modifying my local copy of the lib.js file so that line 69 says this:
```
        ['-json', '-s', '-u', '-F', '-c', '%+.5f'],
```
but I'd love to be able to pass these options in. If I get time next week I'll do a PR or something.

**Comment by ndtreviv** [comment]
I'd also like to be able to pass `-g` to group output properties into their relevant areas.

**Comment by ndtreviv** [comment]
Figured it out. 

To pass the extra options, just do it like all the others (ie: without the `-`). For `-c` though put the format in the same string but include a space:

`ep.readMetadata(image, ["g", "F", "u", "c %+.5f"])`

**Comment by michael-ts** [comment]
@ndtreviv I'm trying to do [ "n", "-File:all" ] but I get an error "Invalid Date".  I added the "n" (I tried before and after the other option) because the GPS coordinates are coming up in an unexpected format - I need decimal.
