### ISSUE TITLE
Calling readMetadata in parallel w/ 100+ items consistently causes trouble

### ISSUE THREAD

**Issue by KyleAMathews** [Sobesednik/node-exiftool#9]
Fixed it by using Async's `mapSeries`.

Before I was fairly consistently seeing a few `{ready[numbers]}` and `{begin[numbers]}` try getting returned which caused an error with JSON.parse.

**Comment by z-vr** [comment]
Fixed in https://github.com/Sobesednik/node-exiftool/releases/tag/v2.0.3
@KyleAMathews could you confirm please.

**Comment by KyleAMathews** [comment]
Yup working now! Looped over ~4500 files w/o a glitch (took 15 seconds fwiw).

I am getting this error now `Warning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit` — is there any easy way to increase the limit from the outside of this lib?

**Comment by z-vr** [comment]
@KyleAMathews should be fixed now in `2.1.1`

**Comment by KyleAMathews** [comment]
@z-vr upgraded and no more eventemitter leaks! Things look really smooth now, thanks!

**Comment by z-vr** [comment]
@KyleAMathews np thanks for testing!
